simpleiot/simpleiot

README.md

envsetup.sh has "siot" now, instead of "app".

README.md: correct shell function prefix

---

api/auth.go
api/db.go
api/devices.go
api/server.go
api/users.go
api/v1.go
cmd/siot/main.go
data/data.go
data/user.go
db/db.go
envsetup.sh
frontend2/src/Pages/Devices.elm
frontend2/src/Pages/Users.elm
frontend2/src/Utils/Styles.elm
go.mod
go.sum

The main changes:
1. Created the user list page, which allows creating new and editing certain properties of existing users. Role functionality is visible and not yet implemented.
2. Started using bolt transactions. Given that each transaction is driven by the needs of the API call being served, it felt right to expose bolthold.Store in package api and diminish the role of package db. The data store itself shouldn't have to think about API calls, and the API shouldn't have to think about transactions. We maintain strict separation between code that serves HTTP requests and code that implements transactions, even though it's all in package api at the moment. It will be easy to move the transactions somewhere else.
Next, I intend to work on orgs.

User list; bolt transactions

---

api/db.go

The frontend is capable of modifying the set of roles of a user in one request. To support this, we have to do several things:
1. Assign UUIDs to roles that do not yet exist and insert them
2. Update existing roles that have been modified
3. Remove roles that have been deleted

api: Update user roles correctly

---

frontend2/src/Global.elm
frontend2/src/Pages/Orgs.elm

The orgs page now refers to global state to get the list of orgs. In addition, it can send a message requesting that the org list be updated. The HTTP request has been moved to the Global module.

Refactor orgs page

---

frontend2/src/Global.elm
frontend2/src/Pages/Devices.elm

This allows us to poll the device list only when the devices page is being viewed.

frontend2: move device update polling to devices page

---

frontend2/src/Global.elm
frontend2/src/Pages/Orgs.elm
frontend2/src/Pages/Users.elm
frontend2/src/User.elm

Main changes:
- Added an error field to the global model when signed in, which is displayed in Layout.elm. This should probably evolve into a "status" indicator.
- Moved role display from users page to orgs page.
- Partial implementation of editing roles.
We may want to consider changing the wire data structures used to encode roles (_data.Role_), so that they are easier for the front end to work with. The SQL-style data isn't a good fit. It may be that the storage types should also be changed.
One of the questions raised by this work is whether a user having multiple roles in an organization means anything. Obviously, the most general approach is to permit this, but that could lead to complexity in implementation if this generality isn't necessary. We could use radio buttons instead of …

frontend2: add roles to orgs page

---

envsetup.sh

This changes GOARCH everywhere if unexported instead surgically set it
for this cmd alone

Do not unset GOARCH globally

---

cmd/siot/main.go
envsetup.sh

This helps guess the version from latest git tag e.g. if tag is v0.0.14
then the version printed will be same. In case this is not set it will
default to 'Development' string
Fixes Issues #88

siot: Implement version in binary

---

data/schema.go
envsetup.sh
frontend/src/Api/Point.elm
frontend/src/Components/NodeModbus.elm
frontend/src/Components/NodeModbusIO.elm
frontend/src/UI/Form.elm
modbus/client.go
modbus/crc.go
modbus/modbus.go
modbus/pdu.go
node/modbus.go
node/node.go
respreader/response-reader.go

Phase 2 of modbus implementation. [Previous PR](https://github.com/simpleiot/simpleiot/pull/110)

Modbus phase 2

---

modbus/modbus.go
modbus/pdu.go
modbus/pdu_test.go
modbus/reg.go

This PR makes a few improvements to the Modbus package:
- Invalid addresses and errors generate proper Modbus exception reports, instead of silently ignoring the request
- `PDU.ProcessRequest` takes an interface for registers, instead of a concrete `*Regs`. This allows the user to supply their own backing store that handles different function codes separately.
- The response for Write Single Coil is fixed to have the correct form.
- Tests are added for these cases.
I think there's a few things I could still do but I didn't want to bite them off in the same PR because I had some questions about how best to implement them:
- The `RegProvider` interface could be split into multiple interfaces, one for each function code, and `ProcessRequest` could use type assertions to check if the …

Improve Modbus functionality

---

go.mod
go.sum

Implement rv32/rv64 support as submitted upstream
https://github.com/creack/goselect/pull/16
Fixes
https://github.com/simpleiot/simpleiot/issues/137

Use forked version of goselect

---

.eslintrc.js
frontend/lib/package-lock.json
frontend/lib/package.json
frontend/lib/siot-nats.js

I also changed some of the eslint rules. Here's why:
- React isn't in this project, so that was removed
- We don't need the special babel parser either. Just use ES2018 (which now has widespread browser support)
- Changed `arrow-parens` and `comma-dangle` to match what prettier does
- `capitalized-comments`, `func-style`, and `no-use-before-define` seem excessive. Some of these can hurt readability in my opinion. I can understand the intent of these rules since JS has weird variable hoisting rules, but even if they aren't well understood by most devs, they rarely cause an issue these days with the advent of `let` and `const` keywords. Also, redefined variables / namespace clobbering are issues caught by a modern linter.
Going forward, I'd recommend using prettier. The biggest change would …

simpleiot-js bug fixes

---

CHANGELOG.md
envsetup.sh
frontend/lib/siot-nats.mjs
frontend/lib/test.mjs

Updated CHANGELOG
simpleiot-js:
- `getNodeChildren` runs recursion serially to utilize cache
- added `sendEdgePoints` API function
- added test for creating a node
- added test for pub/sub node points
envsetup:
- simpleiot-js tests now run linter and preserves store on error
- `siot_dblab` now accepts store parameter

Changes relating to simpleiot-js frontend library

---

client/manager.go
client/node.go
data/decode.go
data/encode.go
data/encode_decode_test.go
data/merge.go

As discussed previously, this PR will allow Points to be encoded / decoded to / from many more Go types, including arrays, maps, and "flat" structs.

Upgraded Point encoder to support many more types

---

data/decode.go
data/merge.go
data/merge_test.go
go.mod

A few things I'd like to note regarding this implementation:
- MergePoints / MergeEdgePoints now calls Decode under the hood (which simplifies things greatly and improves readability of `merge.go`)
- Decode is a bit more complicated now, but I'll explain a few of the more odd things below
- Primitive `setVal` function now sets deleted point (i.e. with `p.Tombstone%2==1`) to the zero value. This is true for array and slice values, although there is a small exception to slices described below
- Decode no longer overwrites fields with `node:"id"` or `node:"parent"` tags if the `input.NodeEdge.ID` or `input.NodeEdge.Parent` value is the empty string
- When decoding to a slice, as mentioned above, we now change the behavior of deleted points. Slices are never allocated / copied unless they are …

Reworked and simplified decode and merge routines

---

data/encode.go
data/encode_decode_test.go
data/time_window_avg_test.go

This function compares two structs of the same type and generates a set of Points representing their differences.
This can be useful when structs are already populated with values and you just need to emit points representing their differences. It can aid in synchronizing with external data sources. As an example use case, I am using this function with the NetworkManager code, as these structs are populated by querying NetworkManager's D-Bus API. I then compare to current configuration to compute which points to emit to update the SIOT tree.

Added DiffPoints function

---

data/decode.go
data/encode.go
data/encode_decode_test.go

Encode notes:
- Set tombstone flag on a point if pointer to primitive is `nil`
- For `nil` pointer to a struct, generate tombstone points for each field in the struct.
Decode notes:
- If entire struct is matched with tombstone points, set pointer to `nil`
- Bugfix: Do not try to re-slice / truncate an array
- Bugfix: When decoding to struct, do not write value for missing point

Allow encode/decoding of pointers to structs and primitives; fix bugs

---

client/network-manager-conn.go
client/network-manager-device.go
client/network-manager.go
client/subject.go

- NetworkManagerConn now has error point type, containing an error message of the last SyncConnections() call
- Errors logged by SyncConnections() are now muted unless connection node point is updated
- NetworkManagerConns are now considered Equal if they produce the same D-Bus settings
Thanks!

network-manager: Many sync improvements

---

CHANGELOG.md
api/client.go
api/http-logger.go
api/nodes.go
client/file-transfer.go
network/ethernet.go
node/onewire-io.go
system/os_version_linux.go
system/timezone.go

The `io/ioutil` package has been deprecated as of Go 1.16 [^1]. This commit replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
[^1]: https://golang.org/doc/go1.16#ioutil
Thanks!

Replace deprecated `io/ioutil` functions

---

client/node.go
cmd/siot/main.go

Thanks!
Closes https://github.com/simpleiot/simpleiot/issues/690

client.ExportNodes now works with `id` of "root"

---

CHANGELOG.md
cmd/siot/main.go
server/args.go

server: Args now accepts a *FlagSet to allow flags to be extended

---

client/db_test.go

Influx DB test now requires the use of INFLUX_AUTH_TOKEN env variable

---

client/db.go
data/history.go

- If history query response fails, try responding again with ErrorMessage
- TagFilters values can now be empty string or a slice of strings
Thanks!

db: Improve Influx history query functionality

---

modbus/client.go
modbus/pdu.go

This PR adds the capability to write multiple regs, for example I would use it like this:
```go
id := byte(1)
regs := modbus.Int32ToRegs([]int32{power}) // power in Watts
err = client.WriteMultipleRegs(id, uint16(47321), uint16(2), regs)
```
Right now only `client.WriteSingleReg` is supported, and at first I thought I'd just use that twice, but this can't be used to write multiple regs since it's a completely different request, as detailed here: https://ozeki.hu/p_5883-mobdbus-function-code-16-write-multiple-holding-registers.html
Not sure about the checklist below, let me know if I should do something more or feel free to add to this PR.
Thanks!

feat(modbus): Add support for writing multiple regs
