- data/sample_averager.go
- data/sample_averager_test.go
This is a sample averaging type similar to the time window averaging type. It stores the total of the value fields of incoming samples and averages them by dividing by the count of samples. It also calculates absolute min and max based on the min and max fields of incoming samples. It includes three methods: `AddSample`, `ResetAverage`, and `GetAverage`.
> Sample Averaging Algorithm

- api/devices.go
- api/key.go
- api/server.go
- api/v1.go
- cmd/siot/main.go
> cmdline option to disable auth and send samples

- envsetup.sh
this helps it when building with Yocto/OE environment
> Fix Cross builds

- go.mod
- modbus/modbus.go
- modbus/pdu.go
- modbus/pdu_test.go
- modbus/rtu.go
- Adds support for Write Multiple Coils and Write Multiple Registers.
- Properly checks packet length only on requests (not on responses, which are often shorter).
- Adds test cases to verify normal and error behavior for all supported function codes.
> Modbus protocol improvements

- go.sum
> go.sum: Add checksum for goselect

- data/point.go
- frontend/src/Api/Node.elm
- frontend/src/Api/Point.elm
- frontend/src/Components/NodeAction.elm
- frontend/src/Components/NodeCondition.elm
- frontend/src/Components/NodeDb.elm
- frontend/src/Components/NodeDevice.elm
- frontend/src/Components/NodeGroup.elm
- frontend/src/Components/NodeMessageService.elm
- frontend/src/Components/NodeModbus.elm
- frontend/src/Components/NodeModbusIO.elm
- frontend/src/Components/NodeRule.elm
- frontend/src/Components/NodeUpstream.elm
- frontend/src/Components/NodeUser.elm
- frontend/src/Components/NodeVariable.elm
- frontend/src/UI/Form.elm
> work on supporting point index in UI

- network/at-commands.go
this gives us time stamps, which is useful for debugging
modem problems
> change modem at command debugging to use log

- api/nodes.go
- cmd/siot/main.go
- data/errors.go
- data/node.go
- db/genji.go
- db/nats-handler.go
- internal/pb/node.pb.go
- internal/pb/node.proto
- nats/node.go
- nats/point.go
needed to move the logic to create edges to client, as there is no reliable way to do this once we have distributed nodes (upstreams)
> proper fix for creating nodes from points

- CHANGELOG.md
- api/nodes.go
- cmd/siot/main.go
- docs/api.md
- docs/configuration.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/Components/NodeUpstream.elm
- nats/debug.go
- nats/node.go
- nats/point.go
- node/modbus-manager.go
- node/modbus.go
- node/node.go
- node/upstream-manager.go
- node/upstream-node.go
- node/upstream.go
- start.go
- store/genji.go
- store/nats-handler.go
this allows us to remove all direct calls to DB code from API, etc.
> Feature switch users to nats api

- CHANGELOG.md
- api/nodes.go
- envsetup.sh
- nats/node.go
These are generally useful operations, so make them available to Go code.
> add mirror/delete/move node to nats package

- CHANGELOG.md
- SUMMARY.md
- api/auth.go
- api/v1.go
- data/point.go
- data/schema.go
- docs/ref/api.md
- docs/ref/frontend.md
- internal/pb/nats-request.proto
- nats/node.go
- start.go
- store/genji.go
- store/nats-handler.go
- system/os_version_nonlinux.go
> use nats for user auth requests (instead of direct calls to DB)

- CHANGELOG.md
- client/built-in.go
- client/client.go
- client/cobs-wrapper.go
- client/serial.go
> continued work on serial MCU work

- client/cobs-wrapper_test.go
- go.mod
- go.sum
> fix cobs package version

- CHANGELOG.md
- api/server.go
- client/signal-generator.go
- data/schema.go
- frontend/src/Api/Node.elm
- frontend/src/Api/Point.elm
- frontend/src/Components/NodeSignalGenerator.elm
- frontend/src/Pages/Top.elm
- frontend/src/UI/Icon.elm
> Fix race condition in http api shutdown

- cmd/siot/main.go
- envsetup.sh
- store/sqlite.go
Along with some misc. fixes / cleanup
> Added `siot_test_frontend_lib` script to envsetup

- .air.toml
- .gitignore
- CHANGELOG.md
- envsetup.sh
- go.mod
- go.sum
- tools/tools.go
> use Air for watching Go files during dev

- CHANGELOG.md
- client/client-state.go
- client/manager.go
- client/rule.go
- client/rule_test.go
> fix issue with client child nodes not initializing properly

- frontend/lib/README.md
- frontend/lib/package.json
- frontend/lib/siot-nats.mjs
Added README for simpleiot-js (closes #505)
simpleiot-js now exports all nats.ws
> simpleiot-js: fix bugs and update docs; push to v0.3.0

- frontend/lib/package-lock.json
- frontend/lib/package.json
This is somewhat useful for users who stumble across the npm package and want to find the source code.
> simpleiot-js: Added repo and homepage fields to package.json

- frontend/lib/package-lock.json
- frontend/lib/package.json
- frontend/lib/siot-nats.mjs
> simpleiot-js: Fix default values for optional arguments

- data/decode.go
- data/encode_decode_test.go
- data/point.go
> Fix array decode issues to zero length array 

- frontend/lib/package-lock.json
- frontend/lib/package.json
- frontend/lib/protobuf/point_pb.js
- frontend/lib/siot-nats.mjs
Added new subscription functions
> Updates to JS library

- CHANGELOG.md
- client/edge.go
- cmd/siot/main.go
- docs/user/installation.md
- frontend/src/Pages/Home_.elm
- install/embed.go
- install/siot.service
> add siot install command

- client/network-manager-conn.go
- client/network-manager-device.go
- client/network-manager.go
- client/network-manager_nonlinux.go
> stub out network manager client on non-linux builds

- client/network-manager.go
> network-manager: Fix silly error handling bug

- frontend/lib/siot-nats.mjs
> simpleiot-js: Do not emit points when point list is empty

- CHANGELOG.md
- client/network-manager-conn.go
- client/network-manager-device.go
- client/network-manager.go
- go.mod
- go.sum
> network-manager: Upgrade to gonetworkmanager v2 and fix some bugs

- CHANGELOG.md
- client/network-manager-conn.go
- client/network-manager-device.go
- client/network-manager.go
> network-manager: Connection's `Managed` flag now controls sync direction

- client/signal-generator.go
> signal-generator: Misc. logging tweaks

- README.md
> switch code stats to use scc

- CHANGELOG.md
- contrib/configs/signal-gen.yaml
- frontend/src/Api/Point.elm
- frontend/src/Components/NodeRaw.elm
- frontend/src/Components/NodeSerialDev.elm
- frontend/src/Pages/Home_.elm
- frontend/src/UI/NodeInputs.elm
> Edit node in raw view

- client/ntp.go
> ntp: Fix bugs in client

- network/at-commands.go
- network/at-commands_test.go
> add additional APN commands

- frontend/lib/package-lock.json
- frontend/lib/package.json
> simpleiot-js: Update deps and push to v1.1

- CHANGELOG.md
- docs/ref/frontend.md
- server/args.go
- server/server.go
> clean up custom UI and add debug option

- client/network-manager.go
> NetworkManager client: Added Description field

- frontend/src/Components/NodeMetrics.elm
> add tag UI to metrics client

- README.md
> fix newsletter link

- CHANGELOG.md
- client/db.go
- data/history.go
- docs/ref/api.md
> WIP: db: Added subscription for Influx history queries

- client/serial.go
> serial: Fix minor race condition

- client/rule_test.go
> work around for #630 without disabling test code

- CHANGELOG.md
- SUMMARY.md
- client/file.go
- data/schema.go
- docs/ref/frontend.md
- docs/user/can.md
- docs/user/file.md
- envsetup.sh
- frontend/elm.json
- frontend/src/Api/Point.elm
- frontend/src/Components/NodeFile.elm
- frontend/src/Components/NodeOptions.elm
- frontend/src/Pages/Home_.elm
> allow file node to store binary files

- CHANGELOG.md
- client/client.go
- client/file.go
- data/schema.go
- frontend/src/Api/Point.elm
- frontend/src/Components/NodeFile.elm
> add file node backend client code

- CHANGELOG.md
- client/serial.go
- docs/ref/api.md
> fix issues with high rate data

- CHANGELOG.md
- client/shelly-io-client.go
- client/shelly-io.go
> fix bug where shelly io enable control option was not working (#739)

- CHANGELOG.md
- client/cobs-wrapper.go
- client/node_test.go
- cmd/siot/main.go
- docs/user/configuration.md
- store/sqlite.go
> Fix import bugs
